### ISSUE TITLE
Release 1.0.4 registrated on NPM crashes due wrong commandBus filename

### ISSUE THREAD

**Issue by emirhg** [erickjth/simple-command-bus#2]
npm -i simple-command-bus resolves to version 1.0.4, but there is not such release on the Git Repository and such version crashes

>Error: Cannot find module './CommandBus'

`ls simple-command-bus/lib/`
> commandBus.js  CommandInterface.js  Command.js  CreateCommandBusProxy.js  exceptions  handler  index.js  Middleware.js  plugins  utils.js

The bug fix is the dev branch but not under version control.

**Comment by erickjth** [comment]
There was a PR that solved this bug. But I just published the version 1.0.5 in npm. Could you try to download the latest version.

**Comment by emirhg** [comment]
Thanks! It works now
