### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by perzanko** [erickjth/simple-command-bus#4]
Hi! Thank you for a great package! We are using it in one small service on production. It works pretty well! 🤓 

Are you going to add the Typescript Typings for a library? It'd be extremely useful for us because we are using TS in all of our projects. Currently, we use `@ts-ignore` 👎

**Comment by erickjth** [comment]
Hi there, great to know it's been helpful for you.

At the moment, I’m not planning on adding support to Typescript because I am not a TS expert. 

Would be helpful if you could give me a boost with that and create a PR with a proposal. It would be so helpful for me.

Best,

Erick
